name = "FreeParaxialPropagation"
uuid = "34432e42-2548-414e-b0ee-13347938ede4"
authors = ["Marcos Gil <marcosgildeoliveira@gmail.com>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
